import {
  ApplicationConfig,
  provideZoneChangeDetection,
  importProvidersFrom,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import {
  LucideAngularModule,
  LogIn,
  LogOut,
  MapPin,
  Calendar,
  Shield,
  Users,
  Lock,
  ChevronRight,
  Crosshair,
  Mail,
  KeyRound,
  UserRound,
  X,
  Eye,
  EyeOff,
  Loader,
  Clock,
  Bell,
  MessageSquare,
  Trash2,
  Plus,
  Minus,
  Target,
  Globe,
  Star,
  ArrowLeft,
  Info,
  ChevronDown,
  ImagePlus,
  CircleAlert,
} from 'lucide-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    importProvidersFrom(
      LucideAngularModule.pick({
        LogIn,
        LogOut,
        MapPin,
        Calendar,
        Shield,
        Users,
        Lock,
        ChevronRight,
        Crosshair,
        Mail,
        KeyRound,
        UserRound,
        X,
        Eye,
        EyeOff,
        Loader,
        Target,
        Globe,
        Star,
        Clock,
        Bell,
        MessageSquare,
        Trash2,
        Plus,
        Minus,
        ArrowLeft,
        Info,
        ChevronDown,
        ImagePlus,
        CircleAlert,
      }),
    ),
  ],
};
